export const GET_BUSINESSES = 'GET_BUSINESSES';
export const GET_BUSINESSES_SUCCESS = 'GET_BUSINESSES_SUCCESS';
export const GET_BUSINESSES_FAILURE = 'GET_BUSINESSES_FAILURE';

export const TOGGLE_FAVORITE_BUSINESS = 'TOGGLE_FAVORITE_BUSINESS';
